laravel.loc/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdminProjectController;
use App\Http\Controllers\AdminTechnologyController;
use App\Http\Controllers\AdminUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);

Route::middleware(['auth', 'user.check'])->group(function () {
    Route::get('/', [ProjectController::class, 'index'])->name('projects');


Route::prefix('profile')->group(function () {
    Route::get('/', [UserController::class, 'edit'])->name('profile');
    Route::post('/', [UserController::class, 'update'])->name('profile.update');
    Route::get('/user', [UserController::class, 'show'])->name('user.show');
    Route::get('/invoice_pdf', [UserController::class, 'invoicePdf'])
        ->name('user.invoicepdf');
});
});

Route::middleware(['auth', 'admin.check'])->group(function () {
    Route::prefix('admin')->group(function () {
        Route::get('/', [AdminController::class, 'index'])->name('admin');
        Route::resource('projects', AdminProjectController::class);
        Route::resource('technologies', AdminTechnologyController::class);
        Route::resource('users', AdminUserController::class);
        Route::get('/invoice_pdf/{user}', [AdminUserController::class, 'invoicePdf'])
            ->name('admin_user.invoicepdf');

    });
});


//Route::get('/', [ProjectController::class, 'index'])->name('projects')->middleware('auth');


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
//Route::get('/admin', [App\Http\Controllers\HomeController::class, 'admin'])->name('admin')->middleware('auth.type:admin');

laravel.loc/app/Http/Controllers/AdminUserController.php
<?php

namespace App\Http\Controllers;

use App\Services\TechnologyService;
use Illuminate\Http\Request;
use App\Services\UserService;
use App\Models\User;
use App\Services\ProjectService;
use App\Services\UserTechnologyService;
use App\Models\UserTechnology;
use View;
use Helper;
use Illuminate\Support\Facades\Auth;
use Mpdf\Mpdf;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;

class AdminUserController extends Controller
{

    /**
     * @var UserService
     */
    private $users;

    /**
     * @var ProjectService
     */
    private $projects;
    /**
     * @var UserTechnologyService
     */
    private $user_technologies;
    /**
     * @var TechnologyService
     */
    private $technologies;

    public function __construct(UserService $users, ProjectService $projects, UserTechnologyService $user_technologies, TechnologyService $technologies) //сюда передается нужный объект сервиса
    {
        $this->users = $users; //сдесь имеем доступ к сервису
        $this->projects = $projects;
        $this->user_technologies = $user_technologies;
        $this->technologies = $technologies;

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        /** @var UserTechnology $userTechnologies */
        return view('admin_user.index',
            [
                "users" => $this->users->getNotAdminUsers(),
                "projects" => $this->projects->all(),
                "technologies" => $this->user_technologies->all(),
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin_user.create',
            [
                "users" => $this->users->all(),
                "projects" => $this->projects->all(),
                "technologies" => $this->technologies->all(),
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStoreRequest $request)
    {
        /** @var User $user */
        $user = $this->users->create($request->all());
        $user->projects()->sync($request->get('projects'));
        $user->technologies()->sync($request->get('technology_id'));

        return redirect()->route('users.show', ["user" => $user])->withSuccess('User #' . $user->id . 'was created!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show($id)
    {
        return view(
            'admin_user.show',
            ["user" => $this->users->findById($id)] //метод возвращает конкретную модель по айдишнику
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin_user.edit',
            [
                "user" => $this->users->findById($id), //метод возвращает конкретную модель по айдишнику

            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        /** @var User $user */
        $user->update($request->except(['_method', '_token', 'project_id']));
        $user->projects()->sync($request->get('project_id'));
        $user->technologies()->sync($request->get('technology_id'));


        return redirect()->route('users.show', ["user" => $user])->withSuccess('User #' . $user->id . 'was updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->users->destroy($id);
        return redirect()->route('users.index')->withSuccess('User #' . $id . 'was deleted!');
    }


    public function invoicePdf($id)
    {
        /** @var User $user */
        $user = $this->users->findById($id);
        $view = View::make(
            'admin_user.invoicepdf',
            [
                "user" => $user,
            ]
        );
        $html = $view->render();
        $mpdf = new Mpdf();
        $mpdf->WriteHTML($html);
        $mpdf->Output("invoiceAdminUser.pdf", "D");

    }
    ///dfdfdf
}

laravel.loc/resources/views/admin_user/create.blade.php
@extends('adminlte::page')

@section('content')
    <form method="POST" action="{{ route('users.store') }}">

        @csrf
        <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="form-group">
                        <label for="user_name">User Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                               id="inputName" value=" {{ '' }} ">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="price">Email</label>
                        <input type="email" name="email" id="email"
                               class="form-control @error('email') is-invalid @enderror" value="{{old('email') }}">
                        @error('email')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="inputStatus">Status</label>
                        <select name="status" class="form-control custom-select @error('status') is-invalid @enderror">
                            <option @if(old('status') && "active" == old('status'))
                                    selected
                                    @endif
                                    value="active">Active
                            </option>
                            <option @if(old('status') && "not active" == old('status'))
                                    selected
                                    @endif
                                    value="not active">Not Active
                            </option>
                        </select>

                        <div class="form-group">
                            <label for="inputStatus">Project</label>
                            <select name="projects"
                                    class="form-control custom-select @error('projects') is-invalid @enderror">
                                @foreach($projects as $project)
                                    <option @if(old('project') && $project->project_name == old('project'))
                                            selected
                                            @endif
                                            value="{{ $project->id }}">{{ $project->project_name }}</option>
                                @endforeach
                            </select>
                            @error('projects')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="inputStatus">User Technology</label>
                            <select name="technology_id"
                                    class="form-control custom-select @error('technology_id') is-invalid @enderror">
                                @foreach($technologies as $technology)
                                    <option
                                        @if(old('technology') && $technology->technology_name == old('technology'))
                                        selected
                                        @endif
                                        value="{{ $technology->id }}">{{ $technology->technology_name }}</option>
                                @endforeach
                            </select>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" name="password" id="password"
                                       class="form-control @error('password') is-invalid @enderror" value="">
                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="password">Confirm Password</label>
                                <input type="password" name="password_confirmation" id="password_confirmation"
                                       class="form-control @error('password_confirmation') is-invalid @enderror"
                                       value="">
                            </div>


                            <input type="submit" value="Create User" class="btn btn-info">
                        </div>
                </form>



@endsection

laravel.loc/resources/views/admin_user/edit.blade.php
@extends('adminlte::page')

@section('content')
    <form method="POST" action="{{ route('users.update', ["user" => $user->id]) }}">
        @method('PUT')
        @csrf
        <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="form-group">
                        <label for="name">User Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                               id="name"
                               value=" {{ $user->name }} ">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">User Email</label>
                        <input type="text" class="form-control @error('email') is-invalid @enderror" name="email"
                               id="email"
                               value=" {{ $user->email }} ">
                        @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="inputStatus">Status</label>
                        <select name="status" class="form-control custom-select @error('status') is-invalid @enderror">
                            <option @if(old('status') && "active" == old('status'))
                                    selected
                                    @endif
                                    value="active">Active
                            </option>
                            <option @if(old('status') && "not active" == old('status'))
                                    selected
                                    @elseif(empty(old('status')) && "not active" === $user->status)
                                    selected
                                    @endif
                                    value="not active">Not Active
                            </option>
                        </select>
                        @error('status')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror

                        <div class="form-group">
                            <label for="inputStatus">User Project</label>
                            <select name="project_id"
                                    class="form-control custom-select @error('project_id') is-invalid @enderror">
                                @foreach($projects as $project)
                                    <option @if(old('project') && $project->project_name == old('project'))
                                            selected
                                            @endif
                                            value="{{ $project->id }}">{{ $project->project_name }}</option>
                                @endforeach
                            </select>

                            <div class="form-group">
                                <label for="inputStatus">User Technology</label>
                                <select name="technology_id"
                                        class="form-control custom-select @error('technology_id') is-invalid @enderror">
                                    @foreach($technologies as $technology)
                                        <option
                                            @if(old('technology') && $technology->technology_name == old('technology'))
                                            selected
                                            @endif
                                            value="{{ $technology->id }}">{{ $technology->technology_name }}</option>
                                    @endforeach
                                </select>


                                @error('status')

                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                                @enderror
                            </div>

                        </div>
                    </div>
                </form>

            </div>
            <input type="submit" value="Save Changes" class="btn btn-info">
        </div>


@stop

laravel.loc/resources/views/admin_user/index.blade.php
@extends('adminlte::page')

@section('content')
    @include('partials.alerts')
    <table id="users" class="table table-bordered table-hover dataTable" role="grid"
           aria-describedby="example2_info">
        <thead>
        <tr role="row">
            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending"
            >Name
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Email
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Email verified at
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >User Projects
            </th>
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >User Technologies
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Type
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Status
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Action
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr role="row">
                <td>{{$user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->email_verified_at }}</td>
                <td>
                    @foreach($user->projects as $project)
                        {{ $project->project_name }}
                    @endforeach
                </td>
                <td>
                    @foreach($user->technologies as $technology)
                        {{ $technology->technology_name }}
                    @endforeach
                </td>
                <td>{{$user->type }}</td>
                <td>{{ $user->status }}</td>
                <td>
                    <div class="btn-group">
                        <a href="{{ route('users.show', ["user" => $user]) }}" type="button"
                           class="btn btn-info">View</a>
                        <a href="{{ route('users.edit', ["user" => $user]) }}" type="button"
                           class="btn btn-info">Edit</a>
                        <form method="POST" action="{{ route('users.destroy', ["user" => $user->id]) }}">
                            @method('DELETE')
                            @csrf
                            <input type="submit" value="delete"  class="btn btn-info">

                        </form>
                    </div>
                </td>
        @endforeach
        </tbody>
    </table>

@stop

laravel.loc/resources/views/admin_user/invoicepdf.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

</head>
<body>
<strong>USER DETAILS</strong>
<div class="row">
        @include('partials.alerts')
        <div class="col-md-12">
            <div class="box-body">
                <strong><i class="fa fa-book margin-r-5"></i> {{ $user->name }} </strong>

                <p class="text-muted">
                    ID is # {{ $user->id }}
                </p>

                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> User Project Name </strong>
                <ul>
                    @foreach($user->projects as $project)
                        <li>{{$project->project_name}}</li>
                    @endforeach
                </ul>
                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> User Technology Name </strong>
                <ul>
                    @foreach($user->technologies as $technology)
                        {{ $technology->technology_name }}
                    @endforeach
                </ul>
                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> Created at </strong>

                <p> {{ $user->created_at }} </p>
                <hr>


                <strong><i class="fa fa-pencil margin-r-5"></i> Updatet at</strong>


                <p>  {{ $user->updated_at }} </p>

                <hr>

                <strong><i class="fa fa-file-text-o margin-r-5"></i> Description</strong>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
            </div>

        </div>
    </div>
</body>
    </div>
</html>

laravel.loc/resources/views/admin_user/show.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        @include('partials.alerts')
        <div class="col-md-12">
            <div class="box-body">
                <strong><i class="fa fa-book margin-r-5"></i> {{ $user->name }} </strong>

                <p class="text-muted">
                    ID is # {{ $user->id }}
                </p>

                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> User Project Name </strong>
                <li>
                    @foreach($user->projects as $project)
                        {{$project->project_name}}
                    @endforeach
                </li>
                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> User Technology Name </strong>
                <li>
                    @foreach($user->technologies as $technology)
                        {{ $technology->technology_name }}
                    @endforeach
                </li>
                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> Created at </strong>

                <p> {{ $user->created_at }} </p>
                <hr>


                <strong><i class="fa fa-pencil margin-r-5"></i> Updatet at</strong>


                <p>  {{ $user->updated_at }} </p>

                <hr>

                <strong><i class="fa fa-file-text-o margin-r-5"></i> Description</strong>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
            </div>
            <a href="{{ route('users.edit', ["user" => $user->id]) }}" type="button" class="btn btn-info">Edit</a>
        </div>
    </div>

    </div>
    <a href="{{ route('admin_user.invoicepdf', ["user" => $user->id]) }}" type="button" class="btn btn-primary">
        <i class="fas fa-download"></i> Generate PDF
    </a>




@stop