laravel.loc/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdminProjectController;
use App\Http\Controllers\AdminTechnologyController;
use App\Http\Controllers\AdminUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);

Route::middleware(['auth', 'user.check'])->group(function () {
    Route::get('/', [ProjectController::class, 'index'])->name('projects');


Route::prefix('profile')->group(function () {
    Route::get('/', [UserController::class, 'edit'])->name('profile');
    Route::post('/', [UserController::class, 'update'])->name('profile.update');
    Route::get('/user', [UserController::class, 'show'])->name('user.show');
    Route::get('/invoice_pdf', [UserController::class, 'invoicePdf'])
        ->name('user.invoicepdf');
});
});

Route::middleware(['auth', 'admin.check'])->group(function () {
    Route::prefix('admin')->group(function () {
        Route::get('/', [AdminController::class, 'index'])->name('admin');
        Route::resource('projects', AdminProjectController::class);
        Route::resource('technologies', AdminTechnologyController::class);
        Route::resource('users', AdminUserController::class);
        Route::get('/invoice_pdf/{user}', [AdminUserController::class, 'invoicePdf'])
            ->name('admin_user.invoicepdf');

    });
});


//Route::get('/', [ProjectController::class, 'index'])->name('projects')->middleware('auth');


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
//Route::get('/admin', [App\Http\Controllers\HomeController::class, 'admin'])->name('admin')->middleware('auth.type:admin');

laravel.loc/app/Http/Controllers/AdminTechnologyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Technology;
use Illuminate\Http\Request;
use App\Services\TechnologyService;
use App\Http\Requests\TechnologyStoreRequest;
use App\Http\Requests\TechnologyUpdateRequest;

class AdminTechnologyController extends Controller
{
    public function __construct(TechnologyService $technologies) //сюда передается нужный объект сервиса
    {
        $this->technologies = $technologies; //сдесь имеем доступ к сервису
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() // метод для отображения данных всех проектов
    {
        return view('admin_technology.index',
            [
                "technologies" => $this->technologies->all(),
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()  // метод для создания
    {
        return view('admin_technology.create',
            [
                "technologies" => $this->technologies->all()

            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(TechnologyStoreRequest $request) // метод для сохранения нового проекта
    {
        $technology = $this->technologies->create($request->all());
        return redirect()->route('technologies.show', ["technology" => $technology->id])->withSuccess('Technology #' . $technology->id . 'was created!');;
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) // этот метод вывод конкретную модель продукта  по айдишнику из метода findById
    {
        return view('admin_technology.show',
            ["technology" => $this->technologies->findById($id)] //метод возвращает конкретную модель по айдишнику
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) // показать форму редактирования
    {

        return view('admin_technology.edit',
            [
                "technology" => $this->technologies->findById($id), //метод возвращает конкретную модель по айдишнику
                //"technology" => $this->technologies->all()
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(TechnologyUpdateRequest $request, $id) // обновить отредактированый
    {
        //dd(11);
        $this->technologies->update($id, $request->except(['_method', '_token']));
        return redirect()->route('technologies.show', ["technology" => $id])->withSuccess('Technology #' . $id . 'was updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->technologies->destroy($id);
        return redirect()->route('technologies.index')->withSuccess('Technologies #' . $id . 'was deleted!');
    }



}

laravel.loc/resources/views/admin_technology/create.blade.php
@extends('adminlte::page')

@section('content')
    <form method="POST" action="{{ route('technologies.store') }}">
        @csrf
        <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="form-group">
                        <label for="technology_name">Create Technology</label>
                        <input type="text" class="form-control @error('technology_name') is-invalid @enderror"
                               name="technology_name" id="technology_name" value="{{ old('technology_name') }}">
                        @error('technology_name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror

                    </div>
                    <button type="submit" onclick="create()" class="btn btn-info">Create Technology</button>
                </form>



@endsection

laravel.loc/resources/views/admin_technology/edit.blade.php
@extends('adminlte::page')

@section('content')
    <form method="POST" action="{{ route('technologies.update', ["technology" => $technology->id]) }}">
        @method('PUT')
        @csrf
        <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="form-group">
                        <label for="technology_name">Technology Name</label>
                        <input type="text" class="form-control @error('technology_name') is-invalid @enderror"
                               name="technology_name" id="technology_name"
                               value="{{ old('technology_name') }}">
                        @error('technology_name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror


                    </div>
                </form>
            </div>
            <input type="submit" value="Save Changes" class="btn btn-info">
        </div>


@stop

laravel.loc/resources/views/admin_technology/index.blade.php
@extends('adminlte::page')

@section('content')
    @include('partials.alerts')
    <table id="technologies" class="table table-bordered table-hover dataTable" role="grid"
           aria-describedby="example2_info">
        <thead>
        <tr role="row">
            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending"
            >Technology ID
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Technology Name
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Created at
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Updated at
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Actions
        </tr>
        </thead>
        <tbody>
        @foreach($technologies as $technology)
            <tr role="row">
                <td>{{ $technology->id }}</td>
                <td>{{ $technology->technology_name }}</td>
                <td>{{ $technology->created_at }}</td>
                <td>{{ $technology->updated_at }}</td>
                <td>
                    <div class="btn-group">
                        <a href="{{ route('technologies.show', ["technology" => $technology->id]) }}" type="button"
                           class="btn btn-info">View</a>
                        <a href="{{ route('technologies.edit', ["technology" => $technology->id]) }}" type="button"
                           class="btn btn-info">Edit</a>
                        <form method="POST" action="{{ route('technologies.destroy', ["technology" => $technology->id]) }}">
                            @method('DELETE')
                            @csrf
                            <input type="submit" value="delete"  class="btn btn-info">
                        </form>
                    </div>
                </td>
        @endforeach
        </tbody>
    </table>

@stop

laravel.loc/resources/views/admin_technology/show.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        @include('partials.alerts')
        <div class="col-md-12">
        <div class="box-body">
            <p> Technology name is <br>
            <strong><i class="fa fa-book margin-r-5"></i> {{ $technology->technology_name }} </strong>
            </p>

            <p class="text-muted">
               Technology ID is # {{ $technology->id }}
            </p>

            <hr>

            <strong><i class="fa fa-pencil margin-r-5"></i> Created at </strong>

            <p> {{ $technology->created_at }} </p>
            <hr>


            <strong><i class="fa fa-pencil margin-r-5"></i> Updatet at</strong>


            <p>  {{ $technology->updated_at }} </p>

            <hr>

            <strong><i class="fa fa-file-text-o margin-r-5"></i> Description</strong>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
        </div>
            <a href="{{ route('technologies.edit', ["technology" => $technology->id]) }}" type="button" class="btn btn-info">Edit</a>
        </div>




@stop